### ISSUE TITLE
Golden Sample ViCase Changes (Moved! Do not work in here!) 2016W23

### ISSUE THREAD

**Issue by bcaswelch** [V-Squared/V-Squared.github.io#136]
Moved → [ Create Last Engineering Change List #44 ](https://github.com/V-Squared/v2-Production/issues/44)

**Possible changes**
1. Make changes to dust filter connector. Use magnetic strip to connect to cover? Many cases currently do this and is well received. 
2. Is the bottom cover easily removable? This could be important for users to replace hard drive. 
3. Braces for the outer shell (less squishy).

**Comment by VillageHubertChen** [comment]
Dear Bobby,

First of all thank you for compiling the Engineering Change List.

Unfortunately this is not the right place. This is: →  Create Last Engineering Change List #44 

Remember I introduced it in the Sprint Kick Off meeting today. It is in the column: "This Sprint" of https://waffle.io/V-Squared/V-Squared.github.io 

Please do the following:
- [ ] Copy paste your original text as new comment to →  Create Last Engineering Change List #44
- [ ] Copy and paste this answer as second comment
- [ ] Answer the following questions: (in a third comment)
1. **What is a Dust Filter Connector?** Do you mean the holding mechanism? If so I am confused, because I showed you that the Dust Filter Holding Frame is clamping the Dust Filter with magnets. Please → https://github.com/V-Squared/v2-Production/issues/11#issuecomment-221780126
2. **Bottom Cover is not easily removable:** Remember, we talked about this one too. Instead we plan to make the motherboard easy removable. You need to open 4 screws and you can remove the motherboard. This however will only work if you choose a motherboard where the cable connectors are suitable and if you choose a cable wiring, so that the cables are long enough. This is not an ideal solution. If we were to make the Bottom Cover easy removable, we would make the housing significantly more complex and more expensive, and assembly will take longer. I am open to talk about this again tomorrow. Please make sure Tom is in that call, as he is the one who need to assemble the PCs. If we were to add this feature, we will add to the assembly time. I feel that the proposed solution is sufficient. We have so many plus points that we can afford a minus.
3. **Braces for the out shell:**
   1. What do you mean by braces? Carry Grips? 
   2. What do you mean by squishy? The fluffy nature of the side grill?
   3. What is the purpose of the braces? Where do they go?

Please note that after you move this I need to spend some time to archive this issue, which is not as straight forward as you think. Please be careful with creating new issues. Please spend the requisite time to check of an issue already exists on the topic.

**Comment by VillageHubertChen** [comment]
# Please do above ASAP

@bcaswelch This is gating Golden Sample. Please make a habit that in the morning when you begin and in the evening you each time clean out your notifications. I do. I guess you should feel how my fast responses make you work smooth. In turn that you are slow on responding to notification makes our work slow and delays Golden Sample.

**Comment by bcaswelch** [comment]
Ok, commented. I'll do better with managing notifications

**Comment by VillageHubertChen** [comment]
Looking forward to it. Closed issue for now.
